name: Test Code
on:
  pull_request:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  run-linter:
    name: Code Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: cd functions && npm ci

      - name: Run linters
        run: cd functions && npm run lint

  run-library:
    needs:
      - run-linter
    name: Cloud Function Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: cd functions && npm ci

      - name: Run build script
        run: cd functions && npm run build
